import { Public_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Excel Mapping",
  description: "Generated by Agent Finance",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${publicSans.variable}`}>
      <body className={`${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
